### POST request to example server
POST http://localhost:8090/api/posts
Content-Type: application/json
X-USER-ID: infinity

{
  "title" : "전통 차 추천 좀 ㅠㅠ",
  "content": "여름에 마시기 좋은 전통차 뭐가 있을까요?",
  "categoryId": 8
}

### GET 특정 post에 대한 모든 것 조회
GET http://localhost:8090/api/posts/1
Content-Type: application/json

### GET 특정 그룹에 속하는 모든 post 중 최신순으로 9개 조회
GET http://localhost:8090/api/posts/all/2
Content-Type: application/json

### GET 특정 그룹에 속하는 모든 post 중 view 많은 순으로 9개 조회
GET http://localhost:8090/api/posts/post-views/2
Content-Type: application/json

### GET 특정 category에 해당하는 모든 post 조회
GET http://localhost:8090/api/posts/post-categories/8
Content-Type: application/json

### GET 특정 category에 해당하는 모든 post view 많은 순으로 조회
GET http://localhost:8090/api/posts/post-categories/8/views
Content-Type: application/json

### PUT 특정 post의 내용물 바꾸기
PUT http://localhost:8090/api/posts/1
Content-Type: application/json
X-USER-ID: infinity

{
  "title" : "이번에 신차",
  "content": "현대에서 신차 나온대, 맞음??",
  "categoryId": 2
}

### DELETE 특정 post 삭제
DELETE http://localhost:8090/api/posts/1
Content-Type: application/json