### POST request to example server
POST http://localhost:8080/api/post
Content-Type: application/json
X-User-Id: infinity

{
  "title" : "전통 차 추천 좀 ㅠㅠ",
  "content": "여름에 마시기 좋은 전통차 뭐가 있을까요?",
  "categoryId": 8
}

### GET
GET http://localhost:8080/api/post/1
Content-Type: application/json

###
GET http://localhost:8080/api/posts/6
Content-Type: application/json

###
PUT http://localhost:8080/api/post/1
Content-Type: application/json
X-User-Id: infinity

{
  "title" : "이번에 신차",
  "content": "현대에서 신차 나온대, 맞음??",
  "categoryId": 2
}

###
DELETE http://localhost:8080/api/post/1
Content-Type: application/json