###로그인 정보 요청

GET http://localhost:8080/api/user/testUser
Content-Type: application/json

###

###유저 등록

POST http://localhost:8080/api/user/register
Content-Type: application/json

{
    "userId": "testUser",
    "password": "test",
    "nickname": "azzy",
    "authorityId": 1
}

###