@baseUrl = http://localhost:8090/api/user

###로그인 정보 요청

GET {{baseUrl}}/testUser
Content-Type: application/json

###유저 닉네임 요청

GET {{baseUrl}}/nickname
Content-Type: application/json
X-USER-ID: testUser

###유저 등록

POST {{baseUrl}}/register
Content-Type: application/json

{
    "userId": "testUser",
    "password": "test",
    "nickname": "azzy",
    "authorityId": 1
}

###유저 닉네임 변경
PUT {{baseUrl}}/change-nickname?newNickname=azzzzz
Content-Type: application/json
X-USER-ID: testUser

###유저 권한 변경
PUT {{baseUrl}}/change-auth?newAuth=2
Content-Type: application/json
X-USER-ID: testUser

###유저 비밀번호 변경
PUT {{baseUrl}}/change-password
Content-Type: application/json
X-USER-ID: testUser

{
    "userId": "testUser",
    "oldPassword": "test",
    "newPassword": "test1"
}

###유저 휴면/비휴면으로 변경
PUT {{baseUrl}}/disable-or-enable
Content-Type: application/json
X-USER-ID: testUser

###유저 탈퇴로 변경
PUT {{baseUrl}}/withdraw
Content-Type: application/json
X-USER-ID: testUser